In [23]:
import csv
import numpy as np
import pandas as pd

def open_csv(filename, d = ','):
    data = []
    
    with open(filename, encoding = 'uft-8') as mData:
        info = csv.reader(mData, delimiter = d)
        
        for row in info:
            data.append(row)
        return data
    
def open_exel(filename):
    voter_cols = ['Precinct','BM','BF','BU','WM','WF','WU','APacM','APacF','APacU','HM','HF','HU','NM','NF','NU','OM','OF','OU','UNKNOWN MALE','UNKNOWN FEMALE','UNKNOWN','TOTAL VOTERS']
    column_range = "B,C,F,I,L,O,R,U,X,AA,AD,AG,AJ,AM, AP,AS, AV, AY, BB, BE,BH, BK,BN"
    return pd.read_excel(filename, header=None, names=voter_cols, index_col=0,  usecols=column_range, skiprows=3)

def population(df):
    df['POW_w_Un'] = df[['BM','BF','BU','APacM','APacF','APacU','HM','HF','HU','NM','NF','NU','OM','OF','OU','UNKNOWN MALE','UNKNOWN FEMALE','UNKNOWN']].sum()
    df['POW_wo_Un'] = df[['BM','BF','BU','APacM','APacF','APacU','HM','HF','HU','NM','NF','NU','OM','OF','OU']].sum()
    df['White'] = df[['WM','WF','WU']].sum()

In [40]:
applingGA = open_exel('./files/GA_November8_2016(CountyPrecinct)/APPLING.xlsx')
population(applingGA)
# print(applingGA.columns)
print(applingGA)
sum_row = applingGA[['BM','BF','BU','WM','WF','WU','APacM','APacF','APacU','HM','HF','HU','NM','NF','NU','OM','OF','OU','UNKNOWN MALE','UNKNOWN FEMALE','UNKNOWN','TOTAL VOTERS']].sum()
df_sum=pd.DataFrame(data=sum_row).T
df_sum=df_sum.reindex(columns=applingGA.columns)
df_sum
# df_final=applingGA.append(df_sum,ignore_index=True)
# applingGA
# df_final

           BM   BF  BU   WM   WF  WU  APacM  APacF  APacU  HM  ...  OM  OF  \
Precinct                                                       ...
1B         36   41   0  538  590   1      1      4      0   8  ...   4   2
1C          8   14   0  369  395   0      0      0      0   7  ...   1   1
2         624  818   0  314  407   0      5      2      0  28  ...   9  10
3A          0    1   0  141  154   0      0      0      0   1  ...   0   0
3A1         8    6   0  219  230   0      0      0      0   0  ...   0   1
3B         74   92   0   75   82   0      0      0      0   0  ...   0   1
3C         84  119   0  483  590   0      9      7      0   7  ...   2   4
4A          4    6   0  177  180   0      1      0      0   0  ...   1   1
4B          1    1   0  184  224   0      0      0      0   0  ...   1   0
4C          2    0   0  182  207   0      0      0      0   0  ...   2   1
4D         22   31   0  432  481   0      5      5      0  10  ...   1   1
5A         38   54   0  417  489   0      0      2      0   7  ...   3   3
5B         47   63   0  247  300   0      3      0      0   4  ...   1   2
5C          4    1   0  177  183   0      0      2      0   3  ...   0   0
88888       2    0   0    0    0   0      0      0      0   0  ...   0   0

          OU  UNKNOWN MALE  UNKNOWN FEMALE  UNKNOWN  TOTAL VOTERS  POW_w_Un  \
Precinct
1B         0            15              12        0          1258       NaN
1C         0             6              11        0           815       NaN
2          0            32              19        0          2290       NaN
3A         0             1               2        0           301       NaN
3A1        0             8               9        0           482       NaN
3B         0             3               2        0           331       NaN
3C         0            14              15        0          1352       NaN
4A         0            10               6        0           388       NaN
4B         0             5               5        0           422       NaN
4C         0             7               7        0           409       NaN
4D         0            21               9        0          1031       NaN
5A         0            15              20        0          1066       NaN
5B         0            12               5        0           689       NaN
5C         0             2               6        0           381       NaN
88888      0             0               0        0             2       NaN

          POW_wo_Un  White
Precinct
1B              NaN    NaN
1C              NaN    NaN
2               NaN    NaN
3A              NaN    NaN
3A1             NaN    NaN
3B              NaN    NaN
3C              NaN    NaN
4A              NaN    NaN
4B              NaN    NaN
4C              NaN    NaN
4D              NaN    NaN
5A              NaN    NaN
5B              NaN    NaN
5C              NaN    NaN
88888           NaN    NaN

[15 rows x 25 columns]

,BM,BF,BU,WM,WF,WU,APacM,APacF,APacU,HM,...,OM,OF,OU,UNKNOWN MALE,UNKNOWN FEMALE,UNKNOWN,TOTAL VOTERS,POW_w_Un,POW_wo_Un,White
0,954,1247,0,3955,4512,1,24,22,0,75,...,25,27,0,151,128,0,11217,NaN,NaN,NaN